package gui.subpanels;

import gui.MainFrame;
import gui.tablemodels.AnalysisBatchTableModel;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author xvasekov
 */
public class AnalysisBatchSubPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalysisBatchSubPanel
     */
    public AnalysisBatchSubPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAnalysisBatch = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonAnalysisBatchRemoveSelectedRows = new javax.swing.JButton();
        scrollPaneAnalysisBatchInside = new javax.swing.JScrollPane();
        tableAnalysisBatch = new javax.swing.JTable();
        buttonRunAnalysisBatch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        panelAnalysisBatch.setPreferredSize(new java.awt.Dimension(1361, 615));

        jLabel1.setText("TODO: add checkboxes");

        buttonAnalysisBatchRemoveSelectedRows.setText("Remove selected");
        buttonAnalysisBatchRemoveSelectedRows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnalysisBatchRemoveSelectedRowsActionPerformed(evt);
            }
        });

        tableAnalysisBatch.setModel(AnalysisBatchTableModel.getInstance());
        TableColumn firstColumn = tableAnalysisBatch.getColumnModel().getColumn(0);
        firstColumn.setMinWidth(10);
        firstColumn.setMaxWidth(50);
        TableColumn secondColumn = tableAnalysisBatch.getColumnModel().getColumn(1);
        secondColumn.setMinWidth(50);
        secondColumn.setMaxWidth(110);
        scrollPaneAnalysisBatchInside.setViewportView(tableAnalysisBatch);

        buttonRunAnalysisBatch.setText("Run analysis batch");
        buttonRunAnalysisBatch.setEnabled(false);
        buttonRunAnalysisBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRunAnalysisBatchActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("TODO (later) dialog with data selection. for now takes what is selected here. and TODO: the plot! not everything into 1.");

        javax.swing.GroupLayout panelAnalysisBatchLayout = new javax.swing.GroupLayout(panelAnalysisBatch);
        panelAnalysisBatch.setLayout(panelAnalysisBatchLayout);
        panelAnalysisBatchLayout.setHorizontalGroup(
            panelAnalysisBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnalysisBatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnalysisBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneAnalysisBatchInside, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
                    .addGroup(panelAnalysisBatchLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAnalysisBatchRemoveSelectedRows)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonRunAnalysisBatch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap())
        );
        panelAnalysisBatchLayout.setVerticalGroup(
            panelAnalysisBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnalysisBatchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAnalysisBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnalysisBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonRunAnalysisBatch)
                        .addComponent(jLabel7))
                    .addGroup(panelAnalysisBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(buttonAnalysisBatchRemoveSelectedRows)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneAnalysisBatchInside, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1374, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAnalysisBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 1374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelAnalysisBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAnalysisBatchRemoveSelectedRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnalysisBatchRemoveSelectedRowsActionPerformed
        ((AnalysisBatchTableModel)(tableAnalysisBatch.getModel())).removeRows(tableAnalysisBatch.getSelectedRows());
    }//GEN-LAST:event_buttonAnalysisBatchRemoveSelectedRowsActionPerformed

    private void buttonRunAnalysisBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRunAnalysisBatchActionPerformed
        MainFrame.getInstance().runModels(true);
    }//GEN-LAST:event_buttonRunAnalysisBatchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnalysisBatchRemoveSelectedRows;
    private javax.swing.JButton buttonRunAnalysisBatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelAnalysisBatch;
    private javax.swing.JScrollPane scrollPaneAnalysisBatchInside;
    private javax.swing.JTable tableAnalysisBatch;
    // End of variables declaration//GEN-END:variables

    public JButton getButtonRunAnalysisBatch() {
        return buttonRunAnalysisBatch;
    }

    public JTable getTableAnalysisBatch() {
        return tableAnalysisBatch;
    }
}
