package gui.subpanels;

import gui.PlotDrawer;
import gui.settingspanels.BinomPropSettingsPanel;
import java.util.List;
import models.BinomProp;
import models.params.BinomPropParams;
import utils.FieldsParser;

public class BayesianSubPanel extends javax.swing.JPanel {

    public BayesianSubPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBayesianSettings = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        panelBinomPropPlot = new javax.swing.JPanel();
        tabbedPaneBinomPropPlot = new javax.swing.JTabbedPane();
        panelBinomPropSettings = new BinomPropSettingsPanel();
        panelBinomPropInfo = new javax.swing.JScrollPane();
        textAreaBinomPropInfo = new javax.swing.JTextArea();
        buttonBinomPropComputePosterior = new javax.swing.JButton();
        buttonBinomPropSimulate = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        textFieldBinomPropPercProbInterval = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        buttonBinomPropPredict = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        textFieldBinomPropNumFutureObs = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        panelBayesianSettings.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panelBinomPropPlot.setLayout(new java.awt.BorderLayout());
        panelBinomPropPlot.add(tabbedPaneBinomPropPlot, java.awt.BorderLayout.CENTER);

        textAreaBinomPropInfo.setColumns(20);
        textAreaBinomPropInfo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaBinomPropInfo.setRows(5);
        textAreaBinomPropInfo.setFocusable(false);
        textAreaBinomPropInfo.setOpaque(false);
        panelBinomPropInfo.setViewportView(textAreaBinomPropInfo);

        buttonBinomPropComputePosterior.setText("Compute posterior");
        buttonBinomPropComputePosterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBinomPropComputePosteriorActionPerformed(evt);
            }
        });

        buttonBinomPropSimulate.setText("Simulate from posterior distr.");
        buttonBinomPropSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBinomPropSimulateActionPerformed(evt);
            }
        });

        jLabel26.setText("and construct the");

        textFieldBinomPropPercProbInterval.setText("90");

        jLabel27.setText("% probability interval");

        buttonBinomPropPredict.setText("Predict");
        buttonBinomPropPredict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBinomPropPredictActionPerformed(evt);
            }
        });

        jLabel28.setText("the distr. of successes in the next");

        textFieldBinomPropNumFutureObs.setText("20");

        jLabel29.setText("observations");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelBinomPropInfo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(panelBinomPropSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonBinomPropComputePosterior)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(buttonBinomPropPredict)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBinomPropNumFutureObs))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(buttonBinomPropSimulate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldBinomPropPercProbInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBinomPropPlot, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBinomPropPlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonBinomPropComputePosterior)
                            .addComponent(panelBinomPropSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBinomPropSimulate)
                            .addComponent(jLabel26)
                            .addComponent(textFieldBinomPropPercProbInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBinomPropPredict)
                            .addComponent(jLabel28)
                            .addComponent(textFieldBinomPropNumFutureObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBinomPropInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelBayesianSettings.addTab("Binomial Proportion", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBayesianSettings, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBayesianSettings, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBinomPropComputePosteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBinomPropComputePosteriorActionPerformed
        List<BinomPropParams> params;
        try {
            params = BinomPropParams.getParamsBinomProp(panelBinomPropSettings);
        } catch (IllegalArgumentException e) {
            return;
        }

        List<String> plots = BinomProp.binomPropComputePosterior(params);
        //TODO odstranit tento hnusny hack
        String info = plots.get(plots.size() - 1);
        plots.remove(plots.size() - 1);

        //draw plots into the right panel
        PlotDrawer.drawBayesToGrid(plots, tabbedPaneBinomPropPlot);

        textAreaBinomPropInfo.setText(info);
    }//GEN-LAST:event_buttonBinomPropComputePosteriorActionPerformed

    private void buttonBinomPropSimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBinomPropSimulateActionPerformed
        List<BinomPropParams> params;
        try {
            params = BinomPropParams.getParamsBinomProp(panelBinomPropSettings);
            if (textFieldBinomPropPercProbInterval.getText().isEmpty()) {
                textAreaBinomPropInfo.setText("<no prediction interval specified>");
                return;
            }
        } catch (IllegalArgumentException e) {
            return;
        }

        List<Double> alphasssRaw = FieldsParser.parseDoubles(textFieldBinomPropPercProbInterval);

        textAreaBinomPropInfo.setText(BinomProp.binomPropSimulate(params, alphasssRaw));
    }//GEN-LAST:event_buttonBinomPropSimulateActionPerformed

    private void buttonBinomPropPredictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBinomPropPredictActionPerformed
        List<BinomPropParams> params;
        try {
            params = BinomPropParams.getParamsBinomProp(panelBinomPropSettings);
            //TODO zlepsit?
            if (textFieldBinomPropNumFutureObs.getText().isEmpty()) {
                textAreaBinomPropInfo.setText("<no number of future observations specified>");
                return;
            }
        } catch (IllegalArgumentException e) {
            return;
        }

        List<Integer> numFutureObsss = FieldsParser.parseIntegers(textFieldBinomPropNumFutureObs);

        List<String> plots = BinomProp.binomPropPredict(params, numFutureObsss);

        PlotDrawer.drawBayesToGrid(plots, tabbedPaneBinomPropPlot);
    }//GEN-LAST:event_buttonBinomPropPredictActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBinomPropComputePosterior;
    private javax.swing.JButton buttonBinomPropPredict;
    private javax.swing.JButton buttonBinomPropSimulate;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane panelBayesianSettings;
    private javax.swing.JScrollPane panelBinomPropInfo;
    private javax.swing.JPanel panelBinomPropPlot;
    private javax.swing.JPanel panelBinomPropSettings;
    private javax.swing.JTabbedPane tabbedPaneBinomPropPlot;
    private javax.swing.JTextArea textAreaBinomPropInfo;
    private javax.swing.JTextField textFieldBinomPropNumFutureObs;
    private javax.swing.JTextField textFieldBinomPropPercProbInterval;
    // End of variables declaration//GEN-END:variables
}
