package gui.subpanels;

import javax.swing.JTextArea;

public class ModelDescriptionsSubPanel extends javax.swing.JPanel {

    public ModelDescriptionsSubPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        textAreaModelsInfo = new javax.swing.JTextArea();

        jLabel23.setText("Models and methods used in the last analysis:");

        textAreaModelsInfo.setEditable(false);
        textAreaModelsInfo.setColumns(20);
        textAreaModelsInfo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaModelsInfo.setLineWrap(true);
        textAreaModelsInfo.setRows(5);
        jScrollPane8.setViewportView(textAreaModelsInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1374, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addGap(0, 1135, Short.MAX_VALUE))
                        .addComponent(jScrollPane8))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea textAreaModelsInfo;
    // End of variables declaration//GEN-END:variables

    public JTextArea getTextAreaModelsInfo() {
        return textAreaModelsInfo;
    }
}
