package gui.subpanels;

import gui.PlotDrawer;
import gui.files.OverwriteFileChooser;
import gui.tablemodels.ResidualsTableModel;
import java.awt.BorderLayout;
import java.io.File;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import models.params.BasicStats;
import org.rosuda.javaGD.JGDBufferedPanel;
import utils.ExcelWriter;

public class ResidualsSubPanel extends javax.swing.JPanel {
    
    private JTable residualsTableLatest;
    private static JGDBufferedPanel gdBufferedPanelPlotResiduals;

    public ResidualsSubPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelResidualsAll = new javax.swing.JPanel();
        panelResidualsPlot = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaResidualsBasicStats = new javax.swing.JTextArea();
        panelResidualsLeft = new javax.swing.JPanel();
        buttonExportResiduals = new javax.swing.JButton();
        panelResiduals = new javax.swing.JPanel();
        scrollPaneResiduals = new javax.swing.JScrollPane();
        panelResidualsRightButtons = new javax.swing.JPanel();
        buttonPlotResiduals = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        listPlotResidualsLegend = new javax.swing.JList();

        gdBufferedPanelPlotResiduals = new JGDBufferedPanel(panelResidualsPlot.getWidth(), panelResidualsPlot.getHeight());
        panelResidualsPlot.add(gdBufferedPanelPlotResiduals, BorderLayout.CENTER);

        javax.swing.GroupLayout panelResidualsPlotLayout = new javax.swing.GroupLayout(panelResidualsPlot);
        panelResidualsPlot.setLayout(panelResidualsPlotLayout);
        panelResidualsPlotLayout.setHorizontalGroup(
            panelResidualsPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelResidualsPlotLayout.setVerticalGroup(
            panelResidualsPlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        textAreaResidualsBasicStats.setColumns(20);
        textAreaResidualsBasicStats.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textAreaResidualsBasicStats.setRows(5);
        jScrollPane5.setViewportView(textAreaResidualsBasicStats);

        buttonExportResiduals.setText("Export");
        buttonExportResiduals.setEnabled(false);
        buttonExportResiduals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportResidualsActionPerformed(evt);
            }
        });

        scrollPaneResiduals.setPreferredSize(new java.awt.Dimension(100, 600));

        javax.swing.GroupLayout panelResidualsLayout = new javax.swing.GroupLayout(panelResiduals);
        panelResiduals.setLayout(panelResidualsLayout);
        panelResidualsLayout.setHorizontalGroup(
            panelResidualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneResiduals, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        panelResidualsLayout.setVerticalGroup(
            panelResidualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneResiduals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelResidualsLeftLayout = new javax.swing.GroupLayout(panelResidualsLeft);
        panelResidualsLeft.setLayout(panelResidualsLeftLayout);
        panelResidualsLeftLayout.setHorizontalGroup(
            panelResidualsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResidualsLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResidualsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResiduals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelResidualsLeftLayout.createSequentialGroup()
                        .addComponent(buttonExportResiduals)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        panelResidualsLeftLayout.setVerticalGroup(
            panelResidualsLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResidualsLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonExportResiduals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResiduals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        buttonPlotResiduals.setText("Plot");
        buttonPlotResiduals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlotResidualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResidualsRightButtonsLayout = new javax.swing.GroupLayout(panelResidualsRightButtons);
        panelResidualsRightButtons.setLayout(panelResidualsRightButtonsLayout);
        panelResidualsRightButtonsLayout.setHorizontalGroup(
            panelResidualsRightButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResidualsRightButtonsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(buttonPlotResiduals)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        panelResidualsRightButtonsLayout.setVerticalGroup(
            panelResidualsRightButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResidualsRightButtonsLayout.createSequentialGroup()
                .addComponent(buttonPlotResiduals)
                .addGap(0, 613, Short.MAX_VALUE))
        );

        listPlotResidualsLegend.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(listPlotResidualsLegend);

        javax.swing.GroupLayout panelResidualsAllLayout = new javax.swing.GroupLayout(panelResidualsAll);
        panelResidualsAll.setLayout(panelResidualsAllLayout);
        panelResidualsAllLayout.setHorizontalGroup(
            panelResidualsAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResidualsAllLayout.createSequentialGroup()
                .addComponent(panelResidualsLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelResidualsRightButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResidualsAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelResidualsPlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelResidualsAllLayout.setVerticalGroup(
            panelResidualsAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResidualsAllLayout.createSequentialGroup()
                .addGroup(panelResidualsAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResidualsLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelResidualsAllLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelResidualsAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResidualsAllLayout.createSequentialGroup()
                                .addComponent(panelResidualsRightButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelResidualsAllLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelResidualsPlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1374, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelResidualsAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelResidualsAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExportResidualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportResidualsActionPerformed
        //TODO refactor - je to to iste ako export forecasts len s premenovanymi premennymi
        JFileChooser fileChooser = new OverwriteFileChooser();
        fileChooser.setSelectedFile(new File("residuals.xls"));
        if (evt.getSource() == buttonExportResiduals) {
            switch (fileChooser.showSaveDialog(this)) {
                case JFileChooser.APPROVE_OPTION:
                File residualsFile = fileChooser.getSelectedFile();
                ExcelWriter.residualsJTableToExcel((ResidualsTableModel)(residualsTableLatest.getModel()), residualsFile);
                break;
                case JFileChooser.CANCEL_OPTION:
                default:
                //nothing
            }
        }

        //a na zaver to disablovat, aby sa na to netukalo furt
        buttonExportResiduals.setEnabled(false);
    }//GEN-LAST:event_buttonExportResidualsActionPerformed

    private void buttonPlotResidualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlotResidualsActionPerformed
        //TODO mozno refaktor a vyhodit do PlotDrawera - aby tam bolo vsetko kreslenie grafov
        //TODO refaktor, ptz je to to iste ako drawPlotGeneral/3, len s inymi objektami trosku

        int[] selectedCols = residualsTableLatest.getSelectedColumns();

        List<BasicStats> basicStats = PlotDrawer.drawPlotsResiduals(
            ((ResidualsTableModel)residualsTableLatest.getModel()).getDataForSelectedCols(selectedCols),
            listPlotResidualsLegend, gdBufferedPanelPlotResiduals,
            panelResidualsPlot.getWidth(), panelResidualsPlot.getHeight(), "plot.ts");
        //        buttonPlotExportPlotResiduals.setEnabled(true);

        //mean, standard deviation, median
        StringBuilder basicStatsString = new StringBuilder();
        for (BasicStats stat : basicStats) {
            basicStatsString.append(stat.toString());
            basicStatsString.append(System.lineSeparator());
        }
        textAreaResidualsBasicStats.setText(basicStatsString.toString());
    }//GEN-LAST:event_buttonPlotResidualsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExportResiduals;
    private javax.swing.JButton buttonPlotResiduals;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList listPlotResidualsLegend;
    private javax.swing.JPanel panelResiduals;
    private javax.swing.JPanel panelResidualsAll;
    private javax.swing.JPanel panelResidualsLeft;
    private javax.swing.JPanel panelResidualsPlot;
    private javax.swing.JPanel panelResidualsRightButtons;
    private javax.swing.JScrollPane scrollPaneResiduals;
    private javax.swing.JTextArea textAreaResidualsBasicStats;
    // End of variables declaration//GEN-END:variables

    public void setResidualsTableLatest(JTable residualsTableLatest) {
        this.residualsTableLatest = residualsTableLatest;
    }

    public static void setGdBufferedPanelPlotResiduals(JGDBufferedPanel gdBufferedPanelPlotResiduals) {
        ResidualsSubPanel.gdBufferedPanelPlotResiduals = gdBufferedPanelPlotResiduals;
    }

    public JButton getButtonExportResiduals() {
        return buttonExportResiduals;
    }

    public JButton getButtonPlotResiduals() {
        return buttonPlotResiduals;
    }

    public JPanel getPanelResiduals() {
        return panelResiduals;
    }

    public JPanel getPanelResidualsLeft() {
        return panelResidualsLeft;
    }

    public JPanel getPanelResidualsPlot() {
        return panelResidualsPlot;
    }

    public JPanel getPanelResidualsRightButtons() {
        return panelResidualsRightButtons;
    }

    public JScrollPane getScrollPaneResiduals() {
        return scrollPaneResiduals;
    }

    
}
