package gui;

public class LoadDataCustomizerPanel extends javax.swing.JPanel {
    
    public enum COLNAMES {
        FIRST_ROW, DUMMY, CUSTOM
    }

    /**
     * Creates new form LoadDataCustomizerPanel
     */
    public LoadDataCustomizerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadioButtonsColnames = new javax.swing.ButtonGroup();
        radioButtonColnamesFirstRow = new javax.swing.JRadioButton();
        checkBoxUseFirstColAsLabels = new javax.swing.JCheckBox();
        radioButtonColnamesDummy = new javax.swing.JRadioButton();
        radioButtonColnamesCustom = new javax.swing.JRadioButton();

        buttonGroupRadioButtonsColnames.add(radioButtonColnamesFirstRow);
        buttonGroupRadioButtonsColnames.add(radioButtonColnamesDummy);
        buttonGroupRadioButtonsColnames.add(radioButtonColnamesCustom);

        radioButtonColnamesFirstRow.setSelected(true);
        radioButtonColnamesFirstRow.setText("use the first row as column names");

        checkBoxUseFirstColAsLabels.setSelected(true);
        checkBoxUseFirstColAsLabels.setText("use the first column as labels for time periods");

        radioButtonColnamesDummy.setText("no column names in the file, use placeholders X1, ..., Xn");

        radioButtonColnamesCustom.setText("no column names in the file, specify custom");
        radioButtonColnamesCustom.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radioButtonColnamesFirstRow)
            .addComponent(checkBoxUseFirstColAsLabels)
            .addComponent(radioButtonColnamesDummy)
            .addComponent(radioButtonColnamesCustom)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(checkBoxUseFirstColAsLabels)
                .addGap(18, 18, 18)
                .addComponent(radioButtonColnamesFirstRow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonColnamesDummy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioButtonColnamesCustom))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRadioButtonsColnames;
    private javax.swing.JCheckBox checkBoxUseFirstColAsLabels;
    private javax.swing.JRadioButton radioButtonColnamesCustom;
    private javax.swing.JRadioButton radioButtonColnamesDummy;
    private javax.swing.JRadioButton radioButtonColnamesFirstRow;
    // End of variables declaration//GEN-END:variables

    public boolean isFirstColumnLabelsAxisX() {
        return checkBoxUseFirstColAsLabels.isSelected();
    }
    
    public COLNAMES getColnamesType() {
        if (radioButtonColnamesFirstRow.isSelected()) {
            return COLNAMES.FIRST_ROW;
        } else if (radioButtonColnamesDummy.isSelected()) {
            return COLNAMES.DUMMY;
        } else { //should not happen for now...
            return COLNAMES.CUSTOM;
        }
    }
}
